linters:
  BorderZero:
    enabled: true
  ColorVariable:
    enabled: true
  DuplicateProperty:
    enabled: true
  ElsePlacement:
    enabled: true
  HexLength:
    enabled: true
  IdSelector:
    enabled: true
  Indentation:
    enabled: true
  LeadingZero:
    enabled: true
  MergeableSelector:
    enabled: true
  NameFormat:
    enabled: true
  PropertySortOrder:
    enabled: false
  PropertySpelling:
    enabled: true
  QualifyingElement:
    enabled: true
  SingleLinePerSelector:
    enabled: true
  SpaceAfterComma:
    enabled: true
  SpaceAfterPropertyColon:
    enabled: true
  SpaceBeforeBrace:
    enabled: true
  SpaceBetweenParens:
    enabled: true
  StringQuotes:
    enabled: true
  TrailingSemicolon:
    enabled: true
  UnnecessaryMantissa:
    enabled: true
  UnnecessaryParentReference:
    enabled: true
  VendorPrefix:
    enabled: false
